### ISSUE TITLE
Blog links are producing 404s

### ISSUE THREAD

**Issue by chrismilleruk** [fhinkel/fhinkel.github.io#1]
Links from the homepage and blog archive appear to be a 'day off'

e.g.
Link: https://fhinkel.rocks/2017/12/06/Speed-up-Your-Node-js-App-with-Native-Addons/
Actual article: https://fhinkel.rocks/2017/12/07/Speed-up-Your-Node-js-App-with-Native-Addons/

**Comment by fhinkel** [comment]
Oh weird, thanks for noticing! I'll look into it.

**Comment by fhinkel** [comment]
Thanks so much for noticing! I explicitly set the timezone in my config and regenerated. That seems to have fixed it. Timezones 😑
