### ISSUE TITLE
Jekyll GH-Pages Theme

### ISSUE THREAD

**Issue by gebeto** [fhinkel/fhinkel.github.io#2]
Hey!) I really like your blog design!

Can I make an jekyll theme from your website? It allows you to write your articles using markdown and it will generate google analytics, seo etc.
What are you think about it? May I make it? (And use MIT license for it)

**Comment by fhinkel** [comment]
Hi, thanks! Sure, feel free to use it.

**Comment by gebeto** [comment]
Thank you very much! :)
